version: '3.7'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - relis-application
      - tomcat
      - bibler

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"

    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

    volumes:
      - ./docker/db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
      - ./data/db:/var/lib/mysql

  tomcat:
    depends_on:
      - db
    image: relis/tomcat-relis
    build:
      context: ./tomcat/
    volumes:
      - ./tomcat_data:/u/relis/public_html/workspace
    networks:
      default:
        aliases:
          - relistomcat
    deploy:
      replicas: 1

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    environment:
      MYSQL_DATABASE: db
      CATALINA_OPTS: '-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      JAVA_OPTS: '-Djava.security.egd=file:///dev/urandom'

  bibler:
    image: relis/bibler:latest
    restart: always
    environment:
      ENV: "prod"
    deploy:
      replicas: 3

      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  relis-application:
    depends_on:
      - db
    image: relis/relis-app
    build:
      context: ./docker/
      args:
        - DOCUMENT_ROOT=/u/relis/public_html
        - DIRECTORY_INDEX=index.php
    env_file:
      - .env
    entrypoint: /usr/local/bin/entrypoint.sh
    restart: always
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    volumes:
      - ../:/u/relis/public_html
