version: '3.7'
services:
  db:
    container_name: relis-db
    image: mariadb
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"

    volumes:
      - ./docker/db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
      - ../:/u/relis/public_html

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./docker/db/config.inc.php:/etc/phpmyadmin/config.inc.php
      - ../:/u/relis/public_html

  tomcat:
    depends_on:
      - db
    image: tomcat:8.5.51-jdk8-openjdk-slim
    volumes:
      - ./docker/tomcat/relis.war:/usr/local/tomcat/webapps/relis.war
      - ../:/u/relis/public_html
    environment:
      MYSQL_DATABASE: db
      CATALINA_OPTS: '-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      JAVA_OPTS: '-Djava.security.egd=file:///dev/urandom'
    ports:
      - 8088:8080

  bibler:
    container_name: bibler
    image: relis/bibler
    restart: always

  relis-application:
    depends_on:
      - db
    image: relis-app
    container_name: relis-app
    build:
      context: ./docker/
      args:
        DIRECTORY_INDEX: index.php
        DOCUMENT_ROOT: /u/relis/public_html
    entrypoint: /usr/local/bin/entrypoint.sh
    ports:
      - 8083:80
    volumes:
      - ../:/u/relis/public_html
    extra_hosts:
      - "host.docker.internal:host-gateway"
